name = "linor-widget-cdn"
type = "javascript"
main = "src/worker.js"
compatibility_date = "2024-01-01"
account_id = "391405e53b8b91539adca3a49084f0b8"

workers_dev = true

[env.production]
name = "linor-widget-cdn-prod"

[env.production.vars]
CACHE_VERSION = "1"
ENVIRONMENT = "production"

[env.staging]
name = "linor-widget-cdn-staging"

[env.staging.vars]
CACHE_VERSION = "1"
ENVIRONMENT = "staging"